-- Payroll Database Schema
-- PURPOSE: Store payroll and employee data
-- CREATED BY: SRA Agent
-- DATE: 2026-05-16

CREATE TABLE HR.EMPLOYEE
(
    EMP_ID              INTEGER NOT NULL PRIMARY KEY,
    EMP_NAME            VARCHAR(30) NOT NULL,
    SALARY              DECIMAL(9,2) NOT NULL,
    TAX_BRACKET         INTEGER NOT NULL,
    CREATED_DATE        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
IN HRSPACE
AUDIT YES
LOCKSIZE PAGE;

CREATE TABLE HR.PAYROLL
(
    PAYROLL_ID          INTEGER NOT NULL PRIMARY KEY,
    EMP_ID              INTEGER NOT NULL,
    GROSS_PAY           DECIMAL(9,2) NOT NULL,
    FEDERAL_TAX         DECIMAL(9,2) NOT NULL,
    STATE_TAX           DECIMAL(9,2) NOT NULL,
    FICA                DECIMAL(9,2) NOT NULL,
    NET_PAY             DECIMAL(9,2) NOT NULL,
    PAY_DATE            DATE NOT NULL,
    CREATED_DATE        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMP_ID) REFERENCES HR.EMPLOYEE(EMP_ID)
)
IN HRSPACE
AUDIT YES;

CREATE INDEX HR.IDX_PAYROLL_DATE
    ON HR.PAYROLL(PAY_DATE DESC)
    USING CLUSTERING;

GRANT SELECT, INSERT, UPDATE ON HR.EMPLOYEE TO ROLE HR_ADMIN;
GRANT SELECT, INSERT ON HR.PAYROLL TO ROLE HR_ADMIN;
